### PR TITLE
adding verbose to component

### PR DESCRIPTION
**Pull request by nazwa**
This needs to be updated as well to make the new verbose option work

### CODE REVIEW

**Comment by apriendeau** [comment]
This is really needs to be merged.

**Comment by yudppp** [comment]
+1

**Comment by peterdeka** [comment]
+1 definetly breaking build

**Comment by mermel** [comment]
+1

**Comment by alikhan-io** [comment]
+1. Can we get additional maintainers on this package? My company will happily allocate time from one or more of our devs to this.

**Comment by apriendeau** [comment]
Same here because a lot of people depend on this pkg being stable. 
-- Austin




On Thu, Jul 23, 2015 at 4:35 PM -0700, "Ali Khan" <notifications@github.com> wrote:












+1. Can we get additional maintainers on this package? My company will happily allocate time from one or more of our devs to this.

**Comment by smaxwellstewart** [comment]
Dude please merge! +1

**Comment by yvasiyarov** [comment]
@apriendeau @alikhan-io I would happy if one of your guys can help me maintain this package
please, contact me: varyous at gmail.com to discuss it in details

**Comment by alikhan-io** [comment]
Awesome will contact shortly

**Pull request merged**
