### PR TITLE
Adding ability to trace blocks of code and whole methods.

### PR DESCRIPTION
**Pull request by jordanshoebox**

### CODE REVIEW

**Comment by yvasiyarov** [comment]
@jordanshoebox thank you for contribution!

**Comment by bfitzsimmons** [comment]
Is this functionality intended to be used instead of wrapping an entire handler?

**Comment by jordanshoebox** [comment]
It's just a bare bones tracer. It's meant to offer flexibility in tracing blocks of code. Not aware of a better way of wrapping a handler other than the trace/defer method. Any ideas?

**Comment by bfitzsimmons** [comment]
I was referring to the agent.WrapHTTPHandler() method.  Does the trace method differ in functionality from that method?  If so, where would I find the results of the trace in the New Relic plugin UI?  I enabled tracing on a method and I'm not finding the results in the UI.

**Comment by jordanshoebox** [comment]
@bfizsimmons functionality is different because its more flexible. You can create a custom dashboard to see the results. I dont know another way to see them

**Comment by bfitzsimmons** [comment]
I see.  I'll try that.

Thanks for the help.

**Comment by jordanshoebox** [comment]
I've done this by selecting Trace/my_trace/* for the metrics. This will show you all the different stats. Hopefully that works for you.

**Comment by bfitzsimmons** [comment]
I'll definitely try that out.

Thanks, again.

**Pull request merged**
